name: PHP Stan

on:
  workflow_call:
    inputs:
      PHP_STAN_LEVEL:
        description: 'PHP Stan level'
        type: number
        required: true
        default: 0
      STOP_ON_ERROR:
        description: 'Stop on error'
        type: boolean
        required: true
        default: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP Stan and save output to file
      uses: GuillaumeFalourd/command-output-file-action@v1.1
      env:
        PHP_STAN_LEVEL: 0
      with:
        command_line: vendor/bin/phpstan --no-progress --error-format=github  analyse -l ${{inputs.PHP_STAN_LEVEL}} src
        output_file_name: phpstan.txt

    - name: Read PHP Stan errors and save count to PHP_STAN_ERRORS_COUNT
      run: |
        echo "PHP_STAN_ERRORS_COUNT=$(cat ./phpstan.txt | grep -o -i ::error | wc -w)" >> $GITHUB_ENV
      continue-on-error: true
    
    - name: Comment PR if there are PHP Stan errors
      if: env.PHP_STAN_ERRORS_COUNT > 0
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          PHPStan -> ${{env.PHP_STAN_ERRORS_COUNT}} errors found. Please fix them before merging.
        comment_tag: phpstan
        mode: recreate

    - name: Break if there are PHP Stan errors
      if: inputs.STOP_ON_ERROR == true
      run: |
        if [ ${{env.PHP_STAN_ERRORS_COUNT}} -gt 0 ]; then exit 1; fi
